name: base
channels:
- conda-forge
dependencies:
- python=3.12
- pytest
- numpy
- matplotlib
- pandas
- seaborn
- scikit-learn
- statsmodels
- jupyter
- jupyterlab
- twisted
- pydot
- music21=6.7.1
- mido
- pydub